<?php // $Id$

/**
 * @file module for adding a link to a block title
**/

// Variable Table Prefex
define('BLOCK_TITLELINK_VARIABLE_PREFIX', 'block_titlelink_');

/**
 * Implementation of hook_form_alter
**/
function block_titlelink_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'block_admin_configure') {
    $block = new stdClass();
    $block->module = $form['module']['#value'];
    $block->delta = $form['delta']['#value'];
    $link = _block_titlelink_get_link($block);
    //Define Titlelink form elements
    $form['settings']['block_titlelink'] = array(
      '#type' => 'fieldset',
      '#title' => t('Block Title Link Settings'),
      '#collapsible' => TRUE,
      '#weight' => 0,
    );
    $form['settings']['block_titlelink']['title_path'] = array(
      '#type' => 'textfield',
      '#title' => t('Title Path'),
      '#default_value' => $link,
      '#description' => t('URL path of Block Title.'),
    );
    //Assign weight to block title so it appears above link
    if (!isset($form['block_settings']['#weight'])) {
      $form['block_settings']['#weight'] = -1;
    }
    $form['#validate'][] = 'block_titlelink_form_validate';
    $form['#submit'][] = 'block_titlelink_form_submit';
  }
}

/**
 * Implementation of hook_validate()
**/
function block_titlelink_form_validate(&$elements, &$form_state, $form_id = NULL) {
  $title_path= trim($form_state['values']['title_path']);
  if(!empty($title_path) && !valid_url($title_path) && !valid_url($title_path,TRUE)) {
    form_set_error('title_path', t('The title path appears to contain an invalid URL.'));
  }
}

/**
 * Implementation of hook_submit()
*/
function block_titlelink_form_submit($form, &$form_state) {
  $module = $form['module']['#value'];
  $delta = $form['delta']['#value'];
  $name = $module . '_' . $delta;
  $title_path = trim($form_state['values']['title_path']);
  if(empty($title_path)) {
    _block_titlelink_delete_link($name);
  }
  else {
    _block_titlelink_save_link($name, $title_path);
  }
}

/**
 * Implementation of hook_preprocess_block
**/
function block_titlelink_preprocess_block(&$vars, $hook) {
  if ($hook == 'block') {
    $vars['block']->title_link = _block_titlelink_get_link($vars['block']);
    $title_link = $vars['block']->title_link;
    if ($title_link != '') {
      $vars['block']->subject = l($vars['block']->subject, $title_link, array('attributes' => array('class' => 'block-title-link'), 'html'=>'true'));
    }
  }
}

/**
 * Function to return a title link of a block
 * @param array $block - Block to search by
 * @return string Title Link
**/
function _block_titlelink_get_link($block) {
  if (!isset($block->module) && !isset($block->delta)) {
    return FALSE;
  }
  $varname = BLOCK_TITLELINK_VARIABLE_PREFIX . $block->module .'_'. $block->delta;
  return variable_get($varname, NULL);
}

/**
 * Function to save a title link block
 * @param string $name - Variable name (module . '_' . delta)
 * @param string $value - A valid drupal path or URL
 * @return void
**/
function _block_titlelink_save_link($name, $value) {
  $varname = BLOCK_TITLELINK_VARIABLE_PREFIX . $name;
  variable_set($varname, $value);
}

/**
 * Function to delete a link variable
 * @param string $name
**/
function _block_titlelink_delete_link($name) {
  $varname = BLOCK_TITLELINK_VARIABLE_PREFIX . $name;
  variable_del($varname);
}
